server:
  port: 15001
spring:
  application:
    name: pay-server
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
