server:
  port: 7003
spring:
  application:
    name: auth-server
#  redis:
#    host: 192.168.211.132
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: ok
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: xzzb
  clientSecret: xzzb
encrypt:
  key-store:
    location: classpath:/myshop.jks
    secret: myshop
    alias: myshop
    password: myshop