server:
  port: 9001
spring:
  application:
    name: order-server
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop_order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ok
  rabbitmq:
    password: guest
    username: guest
    port: 5672
    virtual-host: /
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.zb.mapper: debug