server:
  port: 8001
spring:
  application:
    name: user-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qg_user_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ok
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml